export enum QTLongImageScaleType {
  ZOOM_TYPE_CENTER_INSIDE = 0,
  ZOOM_TYPE_CENTER_ORANGE = 1,
  ZOOM_TYPE_CENTER_OUTSIDE = 2,
  ZOOM_TYPE_CENTER_CUSTOM_ABSOLUTE = 3,
  ZOOM_TYPE_CENTER_CUSTOM_RELATIVE = 4,
  ZOOM_TYPE_CENTER_WIDTH_FIXED = 5,
  ZOOM_TYPE_CENTER_HEIGHT_FIXED = 6,
}
