export enum ESGradientOrientation {
  ES_GRADIENT_ORIENTATION_TOP_BOTTOM = 0,
  ES_GRADIENT_ORIENTATION_TR_BL = 1,
  ES_GRADIENT_ORIENTATION_RIGHT_LEFT = 2,
  ES_GRADIENT_ORIENTATION_BR_TL = 3,
  ES_GRADIENT_ORIENTATION_BOTTOM_TOP = 4,
  ES_GRADIENT_ORIENTATION_BL_TR = 5,
  ES_GRADIENT_ORIENTATION_LEFT_RIGHT = 6,
  ES_GRADIENT_ORIENTATION_TL_BR = 7,
}
