export enum QTSeekBarIndicatorMode {
  QT_SEEK_BAR_INDICATION_MODE_SHOW_WHEN_TOUCH = 0,
  QT_SEEK_BAR_INDICATION_MODE_ALWAYS_HIDE = 1,
  QT_SEEK_BAR_INDICATION_MODE_ALWAYS_SHOW_AFTER_TOUCH = 2,
  QT_SEEK_BAR_INDICATION_MODE_ALWAYS_SHOW = 3,
}
