//
export enum QTListViewItemState {
  QT_LIST_VIEW_ITEM_STATE_DEFAULT = 0,
  QT_LIST_VIEW_ITEM_STATE_ATTACHED = 1,
  QT_LIST_VIEW_ITEM_STATE_BIND = 2,
  QT_LIST_VIEW_ITEM_STATE_UNBIND = 3,
  QT_LIST_VIEW_ITEM_STATE_DETACHED = 4,
}
