export enum QTFocusDirection {
  QT_FOCUS_DIRECTION_BACKWARD = 1,
  QT_FOCUS_DIRECTION_FORWARD = 2,
  QT_FOCUS_DIRECTION_LEFT = 17,
  QT_FOCUS_DIRECTION_UP = 33,
  QT_FOCUS_DIRECTION_RIGHT = 66,
  QT_FOCUS_DIRECTION_DOWN = 130,
}
