export enum QTWaterfallSectionType {
  QT_WATERFALL_SECTION_TYPE_LOADING = -1,
  QT_WATERFALL_SECTION_TYPE_TITLE = 1000,
  QT_WATERFALL_SECTION_TYPE_FLEX = 1002,
  QT_WATERFALL_SECTION_TYPE_LIST = 1003,
  QT_WATERFALL_SECTION_TYPE_TAB = 1003,
  QT_WATERFALL_SECTION_TYPE_INDEPENDENT_ITEM = 1004,
  QT_WATERFALL_SECTION_TYPE_TAB_LIST = 1005,
  QT_WATERFALL_SECTION_TYPE_CARD = 1006,
  QT_WATERFALL_SECTION_TYPE_VUE = 1007,
  QT_WATERFALL_SECTION_TYPE_END = -1001,
  QT_WATERFALL_SECTION_TYPE_BLANK = -1000,
  QT_WATERFALL_SECTION_TYPE_PLUGIN = 1008
}
